### PR TITLE
Added full plotly support and fixed bugs with ggplot2 plots

### PR DESCRIPTION
**Pull request by andbe**
* ceplane ggplot and plotly fixes
* added ceef plotly
* ceac ggplot and plotly fixes
* added contour, contour2 plotly
* fixed contour, contour2 ggplot
* added bcea.plot plotly
* added CEriskav plotly

### CODE REVIEW

**Comment by giabaio** [comment]
Thanks, @andbe! Can you please check the problems with the checks (see above)? I think the NOTEs are fine --- I have just added the file `CITATION.cff` (which is specific to `GitHub`, I think) to `.Rbuildignore`, so that would go away. There are a bunch of other errors, though (to do with things like `no visible global function definition` or `no vising binding`), here and there... We're trying to keep this repo as clean as possible so that when we're ready with all the changes we can submit to CRAN with minimal overhead...

Thanks!

**Comment by giabaio** [comment]
Had tested but yes, there are some errors thrown in here and there. Reverted to the previous commit and reopening this.

Thanks

**Comment by andbe** [comment]
I went through it again and cannot see the errors likely due to my work laptop configuration... I get a ```SSL connect error - cannot open the connection to 'http://cran.rstudio.com//web/packages/packages.rds' Execution halted```
but I still see 0 errors, 0 warnings and 0 notes so that's... misleading at best.

I will try with my personal pc - sorry about it!

**Comment by giabaio** [comment]
No worries and thank you for this! Let me know if I can do anything at my end!

**Pull request merged**
