### PR TITLE
(Re-)added BCEAweb and example csv files

### PR DESCRIPTION
**Pull request by andbe**

### CODE REVIEW

**Comment by giabaio** [comment]
Sorry @andbe  --- I haven't fully advertised this, but I was thinking maybe it's just easier to have `BCEAweb` as a separate add-on? I have created a separate repo ([https://github.com/giabaio/BCEAweb](https://github.com/giabaio/BCEAweb)) and made the package installable from `r-universe.dev` ([https://giabaio.r-universe.dev/BCEAweb](https://giabaio.r-universe.dev/BCEAweb)) --- could we leave it like this? I think it would be easier to separate out `BCEA` from `BCEAweb`? What do we think?

**Comment by andbe** [comment]
> Sorry @andbe --- I haven't fully advertised this, but I was thinking maybe it's just easier to have `BCEAweb` as a separate add-on? I have created a separate repo (https://github.com/giabaio/BCEAweb) and made the package installable from `r-universe.dev` (https://giabaio.r-universe.dev/BCEAweb) --- could we leave it like this? I think it would be easier to separate out `BCEA` from `BCEAweb`? What do we think?

No problem at all - closing the PR and I'll look into merging the changes into the other repo

**Comment by giabaio** [comment]
[like]  Baio, Gianluca reacted to your message:
________________________________

**Comment by giabaio** [comment]
Thank you!

---

Gianluca Baio
Professor of Statistics and Health Economics | Head of Department


Department of Statistical Science | University College London
1-19 Torrington Place, London, WC1E 6BT, UK
Twitter: @stats_ucl<https://twitter.com/stats_UCL> | Instagram: @stats_UCL<https://instagram.com/ucl.stats/>


Telephone: +44(0)20 7679 1248 (internal: 41248)
Website: http://www.homepages.ucl.ac.uk/~ucakgba
Blog: https://gianluca.statistica.it/blog/
Book a meeting with me: https://book.morgen.so/gianlucabaio/book-me

________________________________

**Pull request closed without merging**
